version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test: 
    executor: node/default 
    docker:
      - image: circleci/node
        environment:
          DATABASE_URL: postgresql://circleci@localhost/main
      - image: circleci/postgres:15.0
        environment:
          PGHOST: localhost
          PGUSER: circleci
          POSTGRES_USER: circleci
          POSTGRES_DB: main
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Wait for db to run
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - node/install:
          node-version: "16.15.1"
      - run:
          command: npm i
          name: Run installation of packages
      - run:
          command: npm run test 
          name: Run tests
workflows:
  my-custom-workflow:
    jobs:
      - build_and_test            
